
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class CRUD extends javax.swing.JFrame {

    /**
     * Creates new form CRUD
     */
    public CRUD() {
        initComponents();
        String q3="select * from details";
       try{
            DefaultTableModel tdf1=(DefaultTableModel) table.getModel();
        Conn c1=new Conn();
        ResultSet rs2 = c1.s.executeQuery(q3);
            while (rs2.next()) {
                String name1=rs2.getString("name");
                String id1=rs2.getString("id");
                String batch1=rs2.getString("batch");
                String dept1=rs2.getString("department");
                String cgpa1=rs2.getString("cgpa");
                String tb[] = {name1,id1,batch1,dept1,cgpa1};
                tdf1.addRow(tb);
            }
       }catch(Exception e){}
    }

    public void fill(){
        nametxt.setText("");
        idtxt.setText("");
        batchtxt.setText("");
        depttxt.setText("");
        cgpatxt.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        idtxt = new javax.swing.JTextField();
        batchtxt = new javax.swing.JTextField();
        depttxt = new javax.swing.JTextField();
        cgpatxt = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(200, 100));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Simple Personal Details");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 290, 37));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 116, 102, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 102, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Batch");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 198, 102, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Department");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 102, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("CGPA");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 102, 20));

        nametxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(nametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 116, 210, 30));

        idtxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(idtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 158, 210, 30));

        batchtxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(batchtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 198, 210, 30));

        depttxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(depttxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 242, 210, 30));

        cgpatxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(cgpatxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 285, 210, 30));

        add.setBackground(new java.awt.Color(255, 255, 255));
        add.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 379, 77, -1));

        update.setBackground(new java.awt.Color(255, 255, 255));
        update.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 379, -1, -1));

        delete.setBackground(new java.awt.Color(255, 255, 255));
        delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 379, -1, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "ID", "Batch", "Department", "CGPA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setResizable(false);
            table.getColumnModel().getColumn(1).setResizable(false);
            table.getColumnModel().getColumn(2).setResizable(false);
            table.getColumnModel().getColumn(3).setResizable(false);
            table.getColumnModel().getColumn(4).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 66, 536, 388));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/maron.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
       String name=nametxt.getText();
       String id=idtxt.getText();
       String batch=batchtxt.getText();
       String dept=depttxt.getText();
       String cgpa=cgpatxt.getText();
       try{
           Conn c1=new Conn();
           String str="insert into details values('"+name+"','"+id+"','"+batch+"','"+dept+"','"+cgpa+"')";
           c1.s.executeUpdate(str);
           JOptionPane.showMessageDialog(null,"Details Added Successfully!");
       DefaultTableModel tdf=(DefaultTableModel) table.getModel();
       tdf.setRowCount(0);
       String q3="select * from details";
        ResultSet rs2 = c1.s.executeQuery(q3);
            while (rs2.next()) {
                name=rs2.getString("name");
                id=rs2.getString("id");
                batch=rs2.getString("batch");
                dept=rs2.getString("department");
                cgpa=rs2.getString("cgpa");
                String tb[] = {name,id,batch,dept,cgpa};
                tdf.addRow(tb);
            }
            fill();
    }catch(Exception e){}
    }//GEN-LAST:event_addActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        String name=nametxt.getText();
       String id=idtxt.getText();
       String batch=batchtxt.getText();
       String dept=depttxt.getText();
       String cgpa=cgpatxt.getText();
       try{
           Conn c1=new Conn();
           String str="update details set id='"+id+"',batch='"+batch+"',department='"+dept+"',cgpa='"+cgpa+"' where name='"+name+"'";
           c1.s.executeUpdate(str);
           DefaultTableModel tdf=(DefaultTableModel) table.getModel();
           tdf.setValueAt(name, table.getSelectedRow(), 0);
           tdf.setValueAt(id, table.getSelectedRow(), 1);
           tdf.setValueAt(batch, table.getSelectedRow(), 2);
           tdf.setValueAt(dept, table.getSelectedRow(), 3);
           tdf.setValueAt(cgpa, table.getSelectedRow(), 4);
           JOptionPane.showMessageDialog(null,"Details updated Successfully!");
           fill();
       }catch(Exception e){}
    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        String name=nametxt.getText();
       String id=idtxt.getText();
       try{
           Conn c1=new Conn();
           String str="delete from details where name='"+name+"' and id='"+id+"'";
           c1.s.executeUpdate(str);
           DefaultTableModel tdf=(DefaultTableModel) table.getModel();
           tdf.removeRow(table.getSelectedRow());
           JOptionPane.showMessageDialog(null,"Details deleted Successfully!");
           fill();
       }catch(Exception e){}
    }//GEN-LAST:event_deleteActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        DefaultTableModel tdf=(DefaultTableModel) table.getModel();
        String name=tdf.getValueAt(table.getSelectedRow(),0).toString();
        String id=tdf.getValueAt(table.getSelectedRow(),1).toString();
        String batch=tdf.getValueAt(table.getSelectedRow(),2).toString();
        String dept=tdf.getValueAt(table.getSelectedRow(),3).toString();
        String cgpa=tdf.getValueAt(table.getSelectedRow(),4).toString();
        nametxt.setText(name);
        idtxt.setText(id);
        batchtxt.setText(batch);
        depttxt.setText(dept);
        cgpatxt.setText(cgpa);
    }//GEN-LAST:event_tableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CRUD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JTextField batchtxt;
    private javax.swing.JTextField cgpatxt;
    private javax.swing.JButton delete;
    private javax.swing.JTextField depttxt;
    private javax.swing.JTextField idtxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nametxt;
    private javax.swing.JTable table;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
